import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import Navigation from "@/components/nav/page";

const roboto = Roboto({
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Self Improvement App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
